### ISSUE TITLE
Use InputStream#transferTo?

### ISSUE THREAD

**Issue by danielcompton** [clj-commons/byte-streams#35]
Java 9 has a new method on the InputStream interface: [`transferTo`](https://docs.oracle.com/javase/9/docs/api/java/io/InputStream.html#transferTo-java.io.OutputStream-) to transfer to an OutputStream. I don't know about it's efficiency compared to what's already here, but thought it might be a useful addition to byte-streams? There is also [`readAllBytes`](https://docs.oracle.com/javase/9/docs/api/java/io/InputStream.html#readAllBytes--) which could be useful too.

**Comment by ztellman** [comment]
I don’t think I can reasonably break backwards compatibility to Java 8 for
a while.

**Comment by arnaudgeiser** [comment]
[transferTo](https://github.com/openjdk/jdk/blob/master/src/java.base/share/classes/java/io/InputStream.java#L785-L795) is quite inflexible in terms of API.
Under the hood, it relies on a 8192 bytes byte-array. [1]
It doesn't correspond to the current default we have on `byte-streams` (4096 bytes). 
I would say that's unlikely we'll be able to leverage this method to define the conversion between `InputStream` and `OuputStream` even if we could today consider dropping Java 8 support.

What do you think @KingMob?

[1] : https://github.com/openjdk/jdk/blob/master/src/java.base/share/classes/java/io/InputStream.java#L785-L795

**Comment by KingMob** [comment]
It looks like our [existing transfer fn](https://github.com/clj-commons/byte-streams/blob/70a45b5315f4c1d67e109244cda7ce3b9e5a6b69/src/clj_commons/byte_streams.clj#L666-L685), is doing almost the same thing as `.transferTo` under the hood. They both .read() into a byte array, and .write() that to the OutputStream.

The array size would probably benefit from some micro-tuning for modern page sizes or some such, but I doubt it's a radical difference (or at least, I sure hope so...)

`.readAllBytes` would be convenient, but we can never guarantee a file would fit in memory, so we have to stick with reading/writing in chunks.

I think we can close this, but, @danielcompton, feel free to reopen it if you think we're missing something.
