### ISSUE TITLE
Undeclared behavior for transfer {:close? true}

### ISSUE THREAD

**Issue by lukeneil** [clj-commons/byte-streams#38]
The docstring for transfer documents the behavior of of the :close? flag as the following:

> `close?`     - whether the sink should be closed once the transfer is done, defaults to true.

However, on further inspection, transfer-fn appears to close both the source and sink streams when :close? is set, leading to potentially undesirable behavior if the caller is not expecting the source stream to close.

I would suggest either updating the docstring or behavior to be consistent with the user's expectations.

**Comment by KingMob** [comment]
I think for now, the documentation should be updated to reflect that `transfer` will attempt to close both the source and sink.

**Comment by KingMob** [comment]
Fixed by #44
