### ISSUE TITLE
Lein javac options break on JDKs >= 12

### ISSUE THREAD

**Issue by KingMob** [clj-commons/byte-streams#40]
This line in project.clj is causing the problem: `:javac-options ["-target" "1.6" "-source" "1.6"]`

It's not a blocker for those consuming by jar, it's only if you want to fire up a REPL and poke around the code.

```~/Documents/Code/byte-streams |HEAD✓
❯ jenv shell 12
~/Documents/Code/byte-streams |HEAD✓
❯ lein do clean, compile, repl
Compiling 3 source files to /Users/matthew/Documents/Code/byte-streams/target/classes
warning: [options] bootstrap class path not set in conjunction with -source 6
error: Source option 6 is no longer supported. Use 7 or later.
error: Target option 6 is no longer supported. Use 7 or later.
Compilation of Java sources(lein javac) failed.
```

**Comment by slipset** [comment]
I've moved this from the default profile to the `ci` profile, so this should be fixed now. 
Please reopen if the problem persists
